name: mirage-py3.12

channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- pip
- python==3.12.11
- pip:
    - asdf==4.5.0
    - astropy==7.1.0
    - astroquery==0.4.11
    - bokeh==3.8.0
    - crds==13.0.6
    - grismconf==1.51
    - h5py==3.14.0
    - hotsoss==0.1.10
    - ipython==9.6.0
    - jupyter==1.1.1
    - jwst==1.19.2
    - jwst-backgrounds==1.3.0
    - jwst_gtvt==1.1.1
    - lxml==6.0.2
    - matplotlib==3.10.7
    - nircam_gsim>=1.71
    - numpy==2.2.6
    - photutils==2.3.0
    - pysiaf==0.24.1
    - pytest==8.4.2
    - pyyaml==6.0.3
    - scipy==1.16.2
    - sphinx==8.2.3
    - synphot==1.6.0
    - webbpsf==2.0.0