name: Python Package CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        python -m pip install --upgrade pip
        eval "$(conda shell.bash hook)"
        conda env create --file environment_python_${{ matrix.python-version }}.yml --name my_env
        conda activate my_env
        pip install -e .
        pip install pytest
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate my_env
        pytest tests/