name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

  test:
    name: test (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: ./environment_python_${{ matrix.python-version }}.yml
          cache-env: true
          cache-downloads: true

      - run: pip install -e .

      - run: conda env export

      - run: python -c "import mirage"

      - run: pytest tests/
